#!/bin/bash

# set -e

MININAS_APP_VER=1335

if [ ! -e "scripts/env_setup" ]; then
    echo "please run this script in winsun folder"
    exit 1
fi

source scripts/env_setup

if [ ! -e "staging/linux-image-4.3.3.001+_001_amd64.deb" ]; then
    build_kernel_package
fi

build_netboot_jessie
build_mininas_tarball $MININAS_APP_VER
generate_output


