#!/bin/bash

source /overlay/__post_install

config_apt
install_basic_commands

prepare_layout
install_basic_files
install_samba
create_users_and_groups

install_ssh
install_ssdp
install_keys_and_leds
install_updated_starter

install_mysql
install_proftpd

install_deb_packages
install_python_packages
install_mininas_app    

install_thunder
install_dlna
install_netatalk
install_kernel
do_cleanup 


