#!/bin/bash

source /overlay/__post_install

prepare_layout
link_account_files

config_apt
install_basic_commands

install_basic_files
install_network
install_samba
create_users_and_groups

install_sysupgrade_downloader
install_ssh
install_ssdp
install_keys_and_leds
install_updated_starter

install_mysql
install_proftpd

install_deb_packages
install_python_packages
install_mininas_app    

install_thunder
#install_dlna
#install_qqiot
#install_netatalk
install_test
install_kernel
# enable_systemd_network
disable_exim4
do_cleanup 


