#!/bin/bash

#
# mininas_user_password username password
#
if [ "$#" -ne 2 ]; then
    echo "usage: mininas_user_password username password"
    exit 1
fi

. $MININAS_PREFIX/usr/local/sbin/mininas_common

USERNAME=$1
PASSWORD=$2

getent passwd "$USERNAME"
exit_ne 0 10 "user $USERNAME does NOT exist"

echo "${USERNAME}:${PASSWORD}" | chpasswd
exit_ne 0 2 "internal error, please retry later."

(echo "$PASSWORD"; echo "$PASSWORD") | smbpasswd -a $USERNAME
exit_ne 0 2 "internal error, please retry later."


