#!/bin/bash

#
# Can only be set when mountpoint unmounted
#
if mount | grep "on /mnt/winsun type"; then
    echo "please umount first, or disable mountpoint and reboot."
    exit 1
fi

UUID=$1

#
# check arg
#
if [ -z "$UUID" ]; then
    echo "please provide volume uuid"
    exit 1
fi

#
# check uuid
#
if ls -1 /run/mininas/volumes | grep $UUID; then
    # yes, uuid exists
    :
else
    echo "uuid does not exist"
    exit 1
fi

#
# modify unit file
#
UNITFILE=/lib/systemd/system/mnt-winsun.mount
SWAP=/lib/systemd/system/.mnt-winsun.mount.swp

cat $UNITFILE | sed "s/^What.*/What=UUID=${UUID}/" > $SWAP
mv $SWAP $UNITFILE

#
# daemon reload
#
systemctl daemon-reload

#
# update mountpoint registy
#
mininas_mountpoint_probe
mininas_mountpoint_usage







