#!/bin/bash

DIVERSION=1.0

CHASSIS_PATH=/etc/mininas/chassis/static

ATA_COUNT=$(ls -1 $CHASSIS_PATH/ata | wc -l)

rm -rf /run/mininas/dvm/chassis
mkdir -p /run/mininas/dvm/chassis

for i in $(seq 1 $ATA_COUNT); do

    # create runtime path for ata slot
    RUN_CHASSIS_PATH=/run/mininas/dvm/chassis/$i
    mkdir -p $RUN_CHASSIS_PATH

    RESULT=$(find /sys/$(cat $CHASSIS_PATH/ata/$i) -name sd[a-z])
    
    if [ ! -z "$RESULT" ]; then

        DEVPATH="/dev/${RESULT##*/}"

        # create runtime device file for ata slot
        echo "$DEVPATH" > $RUN_CHASSIS_PATH/path

        # crawl
        UDEVRESULT=$(udevadm info $DEVPATH | grep "^E: " | sed "s/^E: //")
        
        # construct associate array
        declare -A ARRAY

        IFS=$'\n'
        for LINE in $UDEVRESULT; do

            UPPER="${LINE%%=*}"
            KEY="$(echo $UPPER | tr '[:upper:]' '[:lower:]')"
            VALUE="${LINE##*=}"
    
            ARRAY["$KEY"]="$VALUE"
        done

        # disk identity
        if [ ! -z "${ARRAY[id_model]}" ] && [ ! -z "${ARRAY[id_serial_short]}" ]; then
            
            DISK_IDENTITY="${ARRAY[id_model]}_${ARRAY[id_serial_short]}" 
            DISK_IDENTITY_PATH=/etc/mininas/data/dvm/disks/$DISK_IDENTITY

            if [ ! -d $DISK_IDENTITY_PATH ]; then
                mkdir -p $DISK_IDENTITY_PATH
            

            for prop in id_model id_serial_short id_wwn id_revision \
                id_ata_rotation_rate_rpm id_ata_sata id_ata_sata_signal_rate_gen1 \
                id_ata_sata_signal_rate_gen2 id_ata_sata_signal_rate_gen3 ; do

                if [[ -v ARRAY[$prop] ]]; then
                    echo "${ARRAY[$prop]}" > $DISK_IDENTITY_PATH/$prop
                fi
            done

            fi

            ln -s $DISK_IDENTITY_PATH $RUN_CHASSIS_PATH/disk 
        fi

        # file system
        FS_PATH=$RUN_CHASSIS_PATH/fs
        mkdir -p $FS_PATH

        for prop in id_fs_type id_fs_usage id_fs_uuid id_fs_uuid_sub id_btrfs_ready \
            id_part_table_type id_part_table_uuid ; do

            if [[ -v ARRAY[$prop] ]]; then
                echo "${ARRAY[$prop]}" > $FS_PATH/$prop
            fi
        done

        #
        # TODO: quick fix for attr_size
        #
        ATTR_SIZE=$( udevadm info --attribute-walk $DEVPATH | grep "ATTR{size}" | sed -e 's/\s\+ATTR{size}==//' -e 's/^"//' -e 's/"$//' )
        
        echo "$ATTR_SIZE" > $DISK_IDENTITY_PATH/attr_size

        #
        # TODO: quick fix for version (disk information version)
        #
        echo "$DIVERSION" > $DISK_IDENTITY_PATH/di_version
 
    fi

done


