#!/bin/bash

#
# This script assumes that the disk and volume info are 
# correct and up-to-date
#
# Also,the volume uuid in unit file must be correct and up-to-date, 
# modifying uuid when volume is mounted is strictly forbidden.
#
POOLPATH=/run/mininas/dvm/pools/1
CHASSIS=/run/mininas/dvm/chassis
VOLUMES=/run/mininas/dvm/volumes

#
# clear all slot mount state
#
for slot in $( ls -1 $CHASSIS ); do
    echo "0" > $CHASSIS/$slot/mounted
done

#
# clear all volume mount state
#
for vuuid in $(ls -1 $VOLUMES); do
    # not really useful
    # echo "0" > $VOLUMES/$vuuid/mounted
    rm -rf $VOLUMES/$vuuid/mountpoint
done

#
# if there are no uuid file, the pool is empty
# quit
#
if [ ! -f "$POOLPATH/uuid" ]; then

    echo "0" > $POOLPATH/mounted
    exit 0
fi

VOLUME_UUID=$(cat $POOLPATH/uuid)

if echo "$(ls -1 $VOLUMES)" | grep "$VOLUME_UUID" > /dev/null ; then
    :
else
    exit 0
fi

#
# 
#
if mount | grep "on /mnt/1 type" > /dev/null ; then

    echo "1" > $POOLPATH/mounted

    for vuuid in $(ls -1 $VOLUMES); do
        
        if [ "$VOLUME_UUID" = "${vuuid}" ]; then
            
            echo "/mnt/1" > ${VOLUMES}/${VOLUME_UUID}/mountpoint
        
            for slot in $(ls ${VOLUMES}/${VOLUME_UUID}/ready); do
                echo "1" > ${VOLUMES}/${VOLUME_UUID}/ready/${slot}/mounted
            done
        fi
    done
else
    
    echo "0" > $POOLPATH/mounted
fi


