#!/bin/bash

#
# currently only /mnt/1 is supported
# 

WINSUN=/run/mininas/dvm/pools/1
UNITFILE=/lib/systemd/system/mnt-winsun.mount

mkdir -p $WINSUN
rm -rf $WINSUN/*

#
# enabled
#
TEMP=$( systemctl is-enabled mnt-winsun.mount )

if [ "$TEMP" = "enabled" ]; then
    ENABLED=1
else
    ENABLED=0
fi

#
# autostart
#
if grep -P "WantedBy *= *multi-user[.]target" /lib/systemd/system/mnt-winsun.mount; then
    AUTOSTART=1
else
    AUTOSTART=0
fi

#
# what, where, type
#
WHAT=$(cat $UNITFILE | grep -P "^What *=" | sed "s/^What *= *UUID=//")
WHERE=$(cat $UNITFILE | grep -P "^Where *=" | sed -n -e "s/^Where *= *//p")
TYPE=$(cat $UNITFILE | grep -P "^Type *=" | sed -n -e "s/^Type *= *//p")

echo "$ENABLED" > $WINSUN/enabled
echo "$AUTOSTART" > $WINSUN/autostart

if [ ! -z "$WHAT" ]; then

    echo "$WHAT" > $WINSUN/uuid

    if ls -1 /run/mininas/dvm/volumes | grep "$WHAT"; then
        ln -s /run/mininas/dvm/volumes/$WHAT $WINSUN/volume
    fi
fi

echo "$WHERE" > $WINSUN/mountpoint
ln -s $WHERE $WINSUN/root

echo "$TYPE" > $WINSUN/type





