#!/bin/bash

set -e

mkdir -p /overlay
mount -t vfat /dev/sda1 /overlay

source /overlay/__post_install

prepare
config_apt
install_ssh
install_ssdp
install_keys_and_leds
install_updated_starter

create_users
install_mysql
install_samba
install_proftpd

install_deb_packages
install_python_packages
install_mininas_app    

install_thunder
install_dlna
# install_netatalk
install_kernel
do_cleanup 


