#!/bin/sh

set -e

rm -rf /mmc
mkdir /mmc
mount -t ext4 /dev/mmcblk0p1 /mmc

# remove everything start with .. but not .. itself
rm -rf /mmc/..?*

# remove everything start with . but not ..
rm -rf /mmc/.[!.]*

# remove everything not hidden
rm -rf /mmc/*

tar xzf /media/mmcblk0p1.tar.gz -C /mmc

umount /mmc
rm -rf /mmc

echo "done"

