#!/bin/sh

set -e

rm -rf /mmc
mkdir /mmc

DASH=------------------------------------------------

echo ""
echo $DASH
echo "partition mmcblk0"
echo $DASH
(for x in o n p 1 33 76288 n p 2 76289 120800 a 1 p w; do echo $x; done) | busybox-x86_64 fdisk /dev/mmcblk0

# waiting for kernel
sleep 3

mke2fs -F -t ext4 /dev/mmcblk0p1
mke2fs -F -t ext4 /dev/mmcblk0p2
echo "done"

echo ""
echo $DASH
echo "untar mmcblk0p1"
echo $DASH
mount -t ext4 /dev/mmcblk0p1 /mmc
# tar xvf /media/mmcblk0p1.tar -C /mmc
cat /media/mmcblk0p1.tar | pv | tar xf - -C /mmc
umount /mmc
echo "done"

#echo ""
#echo $DASH
#echo "rename hostname"
#echo $DASH
#mkdir /winsun
#mount /dev/mmcblk0p1 /winsun
#echo -e "WinsunTech-\c" > /winsun/etc/hostname
#dd if=/dev/mtdblock0 bs=1 skip=1697765 count=6 >> /winsun/etc/hostname
#echo "done"

echo ""
echo $DASH
echo "untar mmclbk0p2"
echo $DASH
mount -t ext4 /dev/mmcblk0p2 /mmc
# tar xvf /media/mmcblk0p2.tar -C /mmc
cat /media/mmcblk0p2.tar | pv | tar xf - -C /mmc

echo ""
echo $DASH
echo "install qqiot guid and licence"
echo $DASH

dd if=/dev/mtdblock0  of=serialfile bs=1 skip=1697760 count=11
SERIAL=`cat serialfile`
echo "SERIAL:$SERIAL"

if [ -e /mmc/ping/qqiot ] ; then 
cp `find /media/qqiotlicence/licence/ -name G*${SERIAL}*`  /mmc/ping/qqiot/GUID_file.txt
cp `find /media/qqiotlicence/licence/ -name l*${SERIAL}*`  /mmc/ping/qqiot/licence.sign.file.txt
chmod  664 /mmc/ping/qqiot/*.txt
fi

if [ -e /mmc/pong/qqiot ] ; then
cp `find /media/qqiotlicence/licence/ -name G*${SERIAL}*`  /mmc/pong/qqiot/GUID_file.txt
cp `find /media/qqiotlicence/licence/ -name l*${SERIAL}*`  /mmc/pong/qqiot/licence.sign.file.txt
chmod 664 /mmc/pong/qqiot/*.txt
fi
umount /mmc
echo "done"

rm -rf /mmc
